import deepMerge from '@/utilities/deepMerge'
import { Field } from 'payload'

type buttonClassesType = (options?: {
  overrides?: Record<string, unknown>
  condition?: (_: any, siblingData: any) => boolean
}) => Field

export const buttonClasses: buttonClassesType = ({
  condition = () => true,
  overrides = {},
} = {}) => {
  const buttonResult: Field = {
    name: 'buttonClasses',
    type: 'select',
    label: 'Button Classes',
    hasMany: true,
    admin: {
      condition,
    },
    options: [
      { label: 'Rounded Full', value: 'rounded-full' },
      { label: 'Rounded Large', value: 'rounded-lg' },
      { label: 'Rounded Medium', value: 'rounded' },
      { label: 'Rounded Small', value: 'rounded-sm' },
      { label: 'Rounded XL', value: 'rounded-xl' },
      { label: 'Rounded 2XL', value: 'rounded-2xl' },
      { label: 'Rounded 3XL', value: 'rounded-3xl' },
      { label: 'Border', value: 'border' },
      { label: 'Border Width 1', value: 'border-[1px]' },
      { label: 'Border Width 2', value: 'border-2' },
      { label: 'Bordered Dark', value: 'border-dark' },
      //border colors
      { label: 'Bordered Red', value: 'border-red' },
      { label: 'Bordered Green', value: 'border-green' },
      { label: 'Bordered Blue', value: 'border-blue' },
      { label: 'Bordered Yellow', value: 'border-yellow' },
      { label: 'Bordered Indigo', value: 'border-indigo' },
      { label: 'Bordered Purple', value: 'border-purple' },
      { label: 'Bordered Pink', value: 'border-pink' },
      { label: 'Bordered Gray', value: 'border-gray' },
      { label: 'Bordered Black', value: 'border-black' },
      { label: 'Bordered White', value: 'border-white' },
      //background colors
      { label: 'BG Inherit', value: 'bg-inherit' },
      { label: 'BG Current', value: 'bg-current' },
      { label: 'BG Transparent', value: 'bg-transparent' },
      { label: 'BG Black', value: 'bg-black' },
      { label: 'BG White', value: 'bg-white' },
      { label: 'BG Red', value: 'bg-red' },
      { label: 'BG Green', value: 'bg-green' },
      { label: 'BG Blue', value: 'bg-blue' },
      { label: 'BG Yellow', value: 'bg-yellow' },
      { label: 'BG Indigo', value: 'bg-indigo' },
      { label: 'BG Purple', value: 'bg-purple' },
      { label: 'BG Pink', value: 'bg-pink' },
      { label: 'BG Gray', value: 'bg-gray' },
      { label: 'BG Transparent', value: 'bg-transparent' },
      // button text colours
      { label: 'Text Black', value: 'text-black' },
      { label: 'Text White', value: 'text-white' },
      { label: 'Text Red', value: 'text-red' },
      { label: 'Text Green', value: 'text-green' },
      { label: 'Text Blue', value: 'text-blue' },
      { label: 'Text Yellow', value: 'text-yellow' },
      { label: 'Text Indigo', value: 'text-indigo' },
      { label: 'Text Purple', value: 'text-purple' },
      { label: 'Text Pink', value: 'text-pink' },
      { label: 'Text Gray', value: 'text-gray' },
      { label: 'Text White', value: 'text-white' },
      { label: 'Text Transparent', value: 'text-transparent' },
      //hover backgrounds
      { label: 'Hover bg transparent', value: 'hover:bg-transparent' },
      { label: 'Hover bg black', value: 'hover:bg-black' },
      { label: 'Hover bg white', value: 'hover:bg-white' },
      { label: 'Hover txt black', value: 'hover:text-black' },
      { label: 'Hover txt white', value: 'hover:text-white' },
      { label: 'Hover txt red', value: 'hover:text-red' },
      { label: 'Hover txt green', value: 'hover:text-green' },
      { label: 'Hover txt blue', value: 'hover:text-blue' },
      { label: 'Hover txt yellow', value: 'hover:text-yellow' },
      { label: 'Hover txt indigo', value: 'hover:text-indigo' },
      { label: 'Hover txt purple', value: 'hover:text-purple' },
      { label: 'Hover txt pink', value: 'hover:text-pink' },
      { label: 'Hover txt gray', value: 'hover:text-gray' },
      { label: 'Hover txt white', value: 'hover:text-white' },
      { label: 'Hover txt transparent', value: 'hover:text-transparent' },
      //hover border colors
      { label: 'Hover border red', value: 'hover:border-red' },
      { label: 'Hover border green', value: 'hover:border-green' },
      { label: 'Hover border blue', value: 'hover:border-blue' },
      { label: 'Hover border yellow', value: 'hover:border-yellow' },
      { label: 'Hover border indigo', value: 'hover:border-indigo' },
      { label: 'Hover border purple', value: 'hover:border-purple' },
      { label: 'Hover border pink', value: 'hover:border-pink' },
      { label: 'Hover border gray', value: 'hover:border-gray' },
      { label: 'Hover border black', value: 'hover:border-black' },
      { label: 'Hover border white', value: 'hover:border-white' },
      { label: 'Hover border transparent', value: 'hover:border-transparent' },
      { label: 'MT None', value: 'mt-0' },
      { label: 'MT XS', value: 'mt-1' },
      { label: 'MT Small', value: 'mt-2' },
      { label: 'MT Medium', value: 'mt-4' },
      { label: 'MT Large', value: 'mt-6' },
      { label: 'MT XL', value: 'mt-8' },
      { label: 'MT 2XL', value: 'mt-10' },
      { label: 'MT 3XL', value: 'mt-12' },
      { label: 'MT 4XL', value: 'mt-16' },
      { label: 'MT 5XL', value: 'mt-20' },
      { label: 'MT 6XL', value: 'mt-24' },
      { label: 'MT 7XL', value: 'mt-32' },
      { label: 'MT 8XL', value: 'mt-40' },
      { label: 'MD MT None', value: 'md:mt-0' },
      { label: 'MD MT XS', value: 'md:mt-1' },
      { label: 'MD MT Small', value: 'md:mt-2' },
      { label: 'MD MT Medium', value: 'md:mt-4' },
      { label: 'MD MT Large', value: 'md:mt-6' },
      { label: 'MD MT XL', value: 'md:mt-8' },
      { label: 'MD MT 2XL', value: 'md:mt-10' },
      { label: 'MD MT 3XL', value: 'md:mt-12' },
      { label: 'MD MT 4XL', value: 'md:mt-16' },
      { label: 'MD MT 5XL', value: 'md:mt-20' },
      { label: 'MD MT 6XL', value: 'md:mt-24' },
      { label: 'MD MT 7XL', value: 'md:mt-32' },
      { label: 'MD MT 8XL', value: 'md:mt-40' },
      { label: 'LG MT None', value: 'lg:mt-0' },
      { label: 'LG MT XS', value: 'lg:mt-1' },
      { label: 'LG MT Small', value: 'lg:mt-2' },
      { label: 'LG MT Medium', value: 'lg:mt-4' },
      { label: 'LG MT Large', value: 'lg:mt-6' },
      { label: 'LG MT XL', value: 'lg:mt-8' },
      { label: 'LG MT 2XL', value: 'lg:mt-10' },
      { label: 'LG MT 3XL', value: 'lg:mt-12' },
      { label: 'LG MT 4XL', value: 'lg:mt-16' },
      { label: 'LG MT 5XL', value: 'lg:mt-20' },
      { label: 'LG MT 6XL', value: 'lg:mt-24' },
      { label: 'LG MT 7XL', value: 'lg:mt-32' },
      { label: 'LG MT 8XL', value: 'lg:mt-40' },
      { label: 'MB None', value: 'mb-0' },
      { label: 'MB XS', value: 'mb-1' },
      { label: 'MB Small', value: 'mb-2' },
      { label: 'MB Medium', value: 'mb-4' },
      { label: 'MB Large', value: 'mb-6' },
      { label: 'MB XL', value: 'mb-8' },
      { label: 'MB 2XL', value: 'mb-10' },
      { label: 'MB 3XL', value: 'mb-12' },
      { label: 'MB 4XL', value: 'mb-16' },
      { label: 'MB 5XL', value: 'mb-20' },
      { label: 'MB 6XL', value: 'mb-24' },
      { label: 'MB 7XL', value: 'mb-32' },
      { label: 'MB 8XL', value: 'mb-40' },
      // Padding Bottom for Medium Screens
      { label: 'MB (md) - None', value: 'md:mb-0' },
      { label: 'MB (md) - XS (1)', value: 'md:mb-1' },
      { label: 'MB (md) - S (2)', value: 'md:mb-2' },
      { label: 'MB (md) - M (4)', value: 'md:mb-4' },
      { label: 'MB (md) - L (6)', value: 'md:mb-6' },
      { label: 'MB (md) - XL (8)', value: 'md:mb-8' },
      { label: 'MB (md) - 2XL (10)', value: 'md:mb-10' },
      { label: 'MB (md) - 3XL (12)', value: 'md:mb-12' },
      { label: 'MB (md) - 4XL (16)', value: 'md:mb-16' },
      { label: 'MB (md) - 5XL (20)', value: 'md:mb-20' },
      { label: 'MB (md) - 6XL (24)', value: 'md:mb-24' },
      { label: 'MB (md) - 7XL (32)', value: 'md:mb-32' },
      { label: 'MB (md) - 8XL (40)', value: 'md:mb-40' },

      // Padding Bottom for Large Screens
      { label: 'MB (lg) - None', value: 'lg:mb-0' },
      { label: 'MB (lg) - XS (1)', value: 'lg:mb-1' },
      { label: 'MB (lg) - S (2)', value: 'lg:mb-2' },
      { label: 'MB (lg) - M (4)', value: 'lg:mb-4' },
      { label: 'MB (lg) - L (6)', value: 'lg:mb-6' },
      { label: 'MB (lg) - XL (8)', value: 'lg:mb-8' },
      { label: 'MB (lg) - 2XL (10)', value: 'lg:mb-10' },
      { label: 'MB (lg) - 3XL (12)', value: 'lg:mb-12' },
      { label: 'MB (lg) - 4XL (16)', value: 'lg:mb-16' },
      { label: 'MB (lg) - 5XL (20)', value: 'lg:mb-20' },
      { label: 'MB (lg) - 6XL (24)', value: 'lg:mb-24' },
      { label: 'MB (lg) - 7XL (32)', value: 'lg:mb-32' },
      { label: 'MB (lg) - 8XL (40)', value: 'lg:mb-40' },

      { label: 'bg Slate 50', value: 'bg-slate-50' },
      { label: 'bg Slate 100', value: 'bg-slate-100' },
      { label: 'bg Slate 200', value: 'bg-slate-200' },
      { label: 'bg Slate 300', value: 'bg-slate-300' },
      { label: 'bg Slate 400', value: 'bg-slate-400' },
      { label: 'bg Slate 500', value: 'bg-slate-500' },
      { label: 'bg Slate 600', value: 'bg-slate-600' },
      { label: 'bg Slate 700', value: 'bg-slate-700' },
      { label: 'bg Slate 800', value: 'bg-slate-800' },
      { label: 'bg Slate 900', value: 'bg-slate-900' },
      { label: 'bg Slate 950', value: 'bg-slate-950' },
      { label: 'bg Gray 50', value: 'bg-gray-50' },
      { label: 'bg Gray 100', value: 'bg-gray-100' },
      { label: 'bg Gray 200', value: 'bg-gray-200' },
      { label: 'bg Gray 300', value: 'bg-gray-300' },
      { label: 'bg Gray 400', value: 'bg-gray-400' },
      { label: 'bg Gray 500', value: 'bg-gray-500' },
      { label: 'bg Gray 600', value: 'bg-gray-600' },
      { label: 'bg Gray 700', value: 'bg-gray-700' },
      { label: 'bg Gray 800', value: 'bg-gray-800' },
      { label: 'bg Gray 900', value: 'bg-gray-900' },
      { label: 'bg Gray 950', value: 'bg-gray-950' },
      { label: 'bg Zinc 50', value: 'bg-zinc-50' },
      { label: 'bg Zinc 100', value: 'bg-zinc-100' },
      { label: 'bg Zinc 200', value: 'bg-zinc-200' },
      { label: 'bg Zinc 300', value: 'bg-zinc-300' },
      { label: 'bg Zinc 400', value: 'bg-zinc-400' },
      { label: 'bg Zinc 500', value: 'bg-zinc-500' },
      { label: 'bg Zinc 600', value: 'bg-zinc-600' },
      { label: 'bg Zinc 700', value: 'bg-zinc-700' },
      { label: 'bg Zinc 800', value: 'bg-zinc-800' },
      { label: 'bg Zinc 900', value: 'bg-zinc-900' },
      { label: 'bg Zinc 950', value: 'bg-zinc-950' },
      { label: 'bg Neutral 50', value: 'bg-neutral-50' },
      { label: 'bg Neutral 100', value: 'bg-neutral-100' },
      { label: 'bg Neutral 200', value: 'bg-neutral-200' },
      { label: 'bg Neutral 300', value: 'bg-neutral-300' },
      { label: 'bg Neutral 400', value: 'bg-neutral-400' },
      { label: 'bg Neutral 500', value: 'bg-neutral-500' },
      { label: 'bg Neutral 600', value: 'bg-neutral-600' },
      { label: 'bg Neutral 700', value: 'bg-neutral-700' },
      { label: 'bg Neutral 800', value: 'bg-neutral-800' },
      { label: 'bg Neutral 900', value: 'bg-neutral-900' },
      { label: 'bg Neutral 950', value: 'bg-neutral-950' },
      { label: 'bg Stone 50', value: 'bg-stone-50' },
      { label: 'bg Stone 100', value: 'bg-stone-100' },
      { label: 'bg Stone 200', value: 'bg-stone-200' },
      { label: 'bg Stone 300', value: 'bg-stone-300' },
      { label: 'bg Stone 400', value: 'bg-stone-400' },
      { label: 'bg Stone 500', value: 'bg-stone-500' },
      { label: 'bg Stone 600', value: 'bg-stone-600' },
      { label: 'bg Stone 700', value: 'bg-stone-700' },
      { label: 'bg Stone 800', value: 'bg-stone-800' },
      { label: 'bg Stone 900', value: 'bg-stone-900' },
      { label: 'bg Stone 950', value: 'bg-stone-950' },
      { label: 'bg Red 50', value: 'bg-red-50' },
      { label: 'bg Red 100', value: 'bg-red-100' },
      { label: 'bg Red 200', value: 'bg-red-200' },
      { label: 'bg Red 300', value: 'bg-red-300' },
      { label: 'bg Red 400', value: 'bg-red-400' },
      { label: 'bg Red 500', value: 'bg-red-500' },
      { label: 'bg Red 600', value: 'bg-red-600' },
      { label: 'bg Red 700', value: 'bg-red-700' },
      { label: 'bg Red 800', value: 'bg-red-800' },
      { label: 'bg Red 900', value: 'bg-red-900' },
      { label: 'bg Red 950', value: 'bg-red-950' },
      { label: 'bg Orange 50', value: 'bg-orange-50' },
      { label: 'bg Orange 100', value: 'bg-orange-100' },
      { label: 'bg Orange 200', value: 'bg-orange-200' },
      { label: 'bg Orange 300', value: 'bg-orange-300' },
      { label: 'bg Orange 400', value: 'bg-orange-400' },
      { label: 'bg Orange 500', value: 'bg-orange-500' },
      { label: 'bg Orange 600', value: 'bg-orange-600' },
      { label: 'bg Orange 700', value: 'bg-orange-700' },
      { label: 'bg Orange 800', value: 'bg-orange-800' },
      { label: 'bg Orange 900', value: 'bg-orange-900' },
      { label: 'bg Orange 950', value: 'bg-orange-950' },
      { label: 'bg Amber 50', value: 'bg-amber-50' },
      { label: 'bg Amber 100', value: 'bg-amber-100' },
      { label: 'bg Amber 200', value: 'bg-amber-200' },
      { label: 'bg Amber 300', value: 'bg-amber-300' },
      { label: 'bg Amber 400', value: 'bg-amber-400' },
      { label: 'bg Amber 500', value: 'bg-amber-500' },
      { label: 'bg Amber 600', value: 'bg-amber-600' },
      { label: 'bg Amber 700', value: 'bg-amber-700' },
      { label: 'bg Amber 800', value: 'bg-amber-800' },
      { label: 'bg Amber 900', value: 'bg-amber-900' },
      { label: 'bg Amber 950', value: 'bg-amber-950' },
      { label: 'bg Yellow 50', value: 'bg-yellow-50' },
      { label: 'bg Yellow 100', value: 'bg-yellow-100' },
      { label: 'bg Yellow 200', value: 'bg-yellow-200' },
      { label: 'bg Yellow 300', value: 'bg-yellow-300' },
      { label: 'bg Yellow 400', value: 'bg-yellow-400' },
      { label: 'bg Yellow 500', value: 'bg-yellow-500' },
      { label: 'bg Yellow 600', value: 'bg-yellow-600' },
      { label: 'bg Yellow 700', value: 'bg-yellow-700' },
      { label: 'bg Yellow 800', value: 'bg-yellow-800' },
      { label: 'bg Yellow 900', value: 'bg-yellow-900' },
      { label: 'bg Yellow 950', value: 'bg-yellow-950' },
      { label: 'bg Lime 50', value: 'bg-lime-50' },
      { label: 'bg Lime 100', value: 'bg-lime-100' },
      { label: 'bg Lime 200', value: 'bg-lime-200' },
      { label: 'bg Lime 300', value: 'bg-lime-300' },
      { label: 'bg Lime 400', value: 'bg-lime-400' },
      { label: 'bg Lime 500', value: 'bg-lime-500' },
      { label: 'bg Lime 600', value: 'bg-lime-600' },
      { label: 'bg Lime 700', value: 'bg-lime-700' },
      { label: 'bg Lime 800', value: 'bg-lime-800' },
      { label: 'bg Lime 900', value: 'bg-lime-900' },
      { label: 'bg Lime 950', value: 'bg-lime-950' },
      { label: 'bg Green 50', value: 'bg-green-50' },
      { label: 'bg Green 100', value: 'bg-green-100' },
      { label: 'bg Green 200', value: 'bg-green-200' },
      { label: 'bg Green 300', value: 'bg-green-300' },
      { label: 'bg Green 400', value: 'bg-green-400' },
      { label: 'bg Green 500', value: 'bg-green-500' },
      { label: 'bg Green 600', value: 'bg-green-600' },
      { label: 'bg Green 700', value: 'bg-green-700' },
      { label: 'bg Green 800', value: 'bg-green-800' },
      { label: 'bg Green 900', value: 'bg-green-900' },
      { label: 'bg Green 950', value: 'bg-green-950' },
      { label: 'bg Emerald 50', value: 'bg-emerald-50' },
      { label: 'bg Emerald 100', value: 'bg-emerald-100' },
      { label: 'bg Emerald 200', value: 'bg-emerald-200' },
      { label: 'bg Emerald 300', value: 'bg-emerald-300' },
      { label: 'bg Emerald 400', value: 'bg-emerald-400' },
      { label: 'bg Emerald 500', value: 'bg-emerald-500' },
      { label: 'bg Emerald 600', value: 'bg-emerald-600' },
      { label: 'bg Emerald 700', value: 'bg-emerald-700' },
      { label: 'bg Emerald 800', value: 'bg-emerald-800' },
      { label: 'bg Emerald 900', value: 'bg-emerald-900' },
      { label: 'bg Emerald 950', value: 'bg-emerald-950' },
      { label: 'bg Teal 50', value: 'bg-teal-50' },
      { label: 'bg Teal 100', value: 'bg-teal-100' },
      { label: 'bg Teal 200', value: 'bg-teal-200' },
      { label: 'bg Teal 300', value: 'bg-teal-300' },
      { label: 'bg Teal 400', value: 'bg-teal-400' },
      { label: 'bg Teal 500', value: 'bg-teal-500' },
      { label: 'bg Teal 600', value: 'bg-teal-600' },
      { label: 'bg Teal 700', value: 'bg-teal-700' },
      { label: 'bg Teal 800', value: 'bg-teal-800' },
      { label: 'bg Teal 900', value: 'bg-teal-900' },
      { label: 'bg Teal 950', value: 'bg-teal-950' },
      { label: 'bg Cyan 50', value: 'bg-cyan-50' },
      { label: 'bg Cyan 100', value: 'bg-cyan-100' },
      { label: 'bg Cyan 200', value: 'bg-cyan-200' },
      { label: 'bg Cyan 300', value: 'bg-cyan-300' },
      { label: 'bg Cyan 400', value: 'bg-cyan-400' },
      { label: 'bg Cyan 500', value: 'bg-cyan-500' },
      { label: 'bg Cyan 600', value: 'bg-cyan-600' },
      { label: 'bg Cyan 700', value: 'bg-cyan-700' },
      { label: 'bg Cyan 800', value: 'bg-cyan-800' },
      { label: 'bg Cyan 900', value: 'bg-cyan-900' },
      { label: 'bg Cyan 950', value: 'bg-cyan-950' },
      { label: 'bg Sky 50', value: 'bg-sky-50' },
      { label: 'bg Sky 100', value: 'bg-sky-100' },
      { label: 'bg Sky 200', value: 'bg-sky-200' },
      { label: 'bg Sky 300', value: 'bg-sky-300' },
      { label: 'bg Sky 400', value: 'bg-sky-400' },
      { label: 'bg Sky 500', value: 'bg-sky-500' },
      { label: 'bg Sky 600', value: 'bg-sky-600' },
      { label: 'bg Sky 700', value: 'bg-sky-700' },
      { label: 'bg Sky 800', value: 'bg-sky-800' },
      { label: 'bg Sky 900', value: 'bg-sky-900' },
      { label: 'bg Sky 950', value: 'bg-sky-950' },
      { label: 'bg Blue 50', value: 'bg-blue-50' },
      { label: 'bg Blue 100', value: 'bg-blue-100' },
      { label: 'bg Blue 200', value: 'bg-blue-200' },
      { label: 'bg Blue 300', value: 'bg-blue-300' },
      { label: 'bg Blue 400', value: 'bg-blue-400' },
      { label: 'bg Blue 500', value: 'bg-blue-500' },
      { label: 'bg Blue 600', value: 'bg-blue-600' },
      { label: 'bg Blue 700', value: 'bg-blue-700' },
      { label: 'bg Blue 800', value: 'bg-blue-800' },
      { label: 'bg Blue 900', value: 'bg-blue-900' },
      { label: 'bg Blue 950', value: 'bg-blue-950' },
      { label: 'bg Indigo 50', value: 'bg-indigo-50' },
      { label: 'bg Indigo 100', value: 'bg-indigo-100' },
      { label: 'bg Indigo 200', value: 'bg-indigo-200' },
      { label: 'bg Indigo 300', value: 'bg-indigo-300' },
      { label: 'bg Indigo 400', value: 'bg-indigo-400' },
      { label: 'bg Indigo 500', value: 'bg-indigo-500' },
      { label: 'bg Indigo 600', value: 'bg-indigo-600' },
      { label: 'bg Indigo 700', value: 'bg-indigo-700' },
      { label: 'bg Indigo 800', value: 'bg-indigo-800' },
      { label: 'bg Indigo 900', value: 'bg-indigo-900' },
      { label: 'bg Indigo 950', value: 'bg-indigo-950' },
      { label: 'bg Violet 50', value: 'bg-violet-50' },
      { label: 'bg Violet 100', value: 'bg-violet-100' },
      { label: 'bg Violet 200', value: 'bg-violet-200' },
      { label: 'bg Violet 300', value: 'bg-violet-300' },
      { label: 'bg Violet 400', value: 'bg-violet-400' },
      { label: 'bg Violet 500', value: 'bg-violet-500' },
      { label: 'bg Violet 600', value: 'bg-violet-600' },
      { label: 'bg Violet 700', value: 'bg-violet-700' },
      { label: 'bg Violet 800', value: 'bg-violet-800' },
      { label: 'bg Violet 900', value: 'bg-violet-900' },
      { label: 'bg Violet 950', value: 'bg-violet-950' },
      { label: 'bg Purple 50', value: 'bg-purple-50' },
      { label: 'bg Purple 100', value: 'bg-purple-100' },
      { label: 'bg Purple 200', value: 'bg-purple-200' },
      { label: 'bg Purple 300', value: 'bg-purple-300' },
      { label: 'bg Purple 400', value: 'bg-purple-400' },
      { label: 'bg Purple 500', value: 'bg-purple-500' },
      { label: 'bg Purple 600', value: 'bg-purple-600' },
      { label: 'bg Purple 700', value: 'bg-purple-700' },
      { label: 'bg Purple 800', value: 'bg-purple-800' },
      { label: 'bg Purple 900', value: 'bg-purple-900' },
      { label: 'bg Purple 950', value: 'bg-purple-950' },
      { label: 'bg Fuchsia 50', value: 'bg-fuchsia-50' },
      { label: 'bg Fuchsia 100', value: 'bg-fuchsia-100' },
      { label: 'bg Fuchsia 200', value: 'bg-fuchsia-200' },
      { label: 'bg Fuchsia 300', value: 'bg-fuchsia-300' },
      { label: 'bg Fuchsia 400', value: 'bg-fuchsia-400' },
      { label: 'bg Fuchsia 500', value: 'bg-fuchsia-500' },
      { label: 'bg Fuchsia 600', value: 'bg-fuchsia-600' },
      { label: 'bg Fuchsia 700', value: 'bg-fuchsia-700' },
      { label: 'bg Fuchsia 800', value: 'bg-fuchsia-800' },
      { label: 'bg Fuchsia 900', value: 'bg-fuchsia-900' },
      { label: 'bg Fuchsia 950', value: 'bg-fuchsia-950' },
      { label: 'bg Pink 50', value: 'bg-pink-50' },
      { label: 'bg Pink 100', value: 'bg-pink-100' },
      { label: 'bg Pink 200', value: 'bg-pink-200' },
      { label: 'bg Pink 300', value: 'bg-pink-300' },
      { label: 'bg Pink 400', value: 'bg-pink-400' },
      { label: 'bg Pink 500', value: 'bg-pink-500' },
      { label: 'bg Pink 600', value: 'bg-pink-600' },
      { label: 'bg Pink 700', value: 'bg-pink-700' },
      { label: 'bg Pink 800', value: 'bg-pink-800' },
      { label: 'bg Pink 900', value: 'bg-pink-900' },
      { label: 'bg Pink 950', value: 'bg-pink-950' },
      { label: 'bg Rose 50', value: 'bg-rose-50' },
      { label: 'bg Rose 100', value: 'bg-rose-100' },
      { label: 'bg Rose 200', value: 'bg-rose-200' },
      { label: 'bg Rose 300', value: 'bg-rose-300' },
      { label: 'bg Rose 400', value: 'bg-rose-400' },
      { label: 'bg Rose 500', value: 'bg-rose-500' },
      { label: 'bg Rose 600', value: 'bg-rose-600' },
      { label: 'bg Rose 700', value: 'bg-rose-700' },
      { label: 'bg Rose 800', value: 'bg-rose-800' },
      { label: 'bg Rose 900', value: 'bg-rose-900' },
      { label: 'bg Rose 950', value: 'bg-rose-950' },
      { label: 'hover:bg Slate 50', value: 'hover:bg-slate-50' },
      { label: 'hover:bg Slate 100', value: 'hover:bg-slate-100' },
      { label: 'hover:bg Slate 200', value: 'hover:bg-slate-200' },
      { label: 'hover:bg Slate 300', value: 'hover:bg-slate-300' },
      { label: 'hover:bg Slate 400', value: 'hover:bg-slate-400' },
      { label: 'hover:bg Slate 500', value: 'hover:bg-slate-500' },
      { label: 'hover:bg Slate 600', value: 'hover:bg-slate-600' },
      { label: 'hover:bg Slate 700', value: 'hover:bg-slate-700' },
      { label: 'hover:bg Slate 800', value: 'hover:bg-slate-800' },
      { label: 'hover:bg Slate 900', value: 'hover:bg-slate-900' },
      { label: 'hover:bg Slate 950', value: 'hover:bg-slate-950' },
      { label: 'hover:bg Gray 50', value: 'hover:bg-gray-50' },
      { label: 'hover:bg Gray 100', value: 'hover:bg-gray-100' },
      { label: 'hover:bg Gray 200', value: 'hover:bg-gray-200' },
      { label: 'hover:bg Gray 300', value: 'hover:bg-gray-300' },
      { label: 'hover:bg Gray 400', value: 'hover:bg-gray-400' },
      { label: 'hover:bg Gray 500', value: 'hover:bg-gray-500' },
      { label: 'hover:bg Gray 600', value: 'hover:bg-gray-600' },
      { label: 'hover:bg Gray 700', value: 'hover:bg-gray-700' },
      { label: 'hover:bg Gray 800', value: 'hover:bg-gray-800' },
      { label: 'hover:bg Gray 900', value: 'hover:bg-gray-900' },
      { label: 'hover:bg Gray 950', value: 'hover:bg-gray-950' },
      { label: 'hover:bg Zinc 50', value: 'hover:bg-zinc-50' },
      { label: 'hover:bg Zinc 100', value: 'hover:bg-zinc-100' },
      { label: 'hover:bg Zinc 200', value: 'hover:bg-zinc-200' },
      { label: 'hover:bg Zinc 300', value: 'hover:bg-zinc-300' },
      { label: 'hover:bg Zinc 400', value: 'hover:bg-zinc-400' },
      { label: 'hover:bg Zinc 500', value: 'hover:bg-zinc-500' },
      { label: 'hover:bg Zinc 600', value: 'hover:bg-zinc-600' },
      { label: 'hover:bg Zinc 700', value: 'hover:bg-zinc-700' },
      { label: 'hover:bg Zinc 800', value: 'hover:bg-zinc-800' },
      { label: 'hover:bg Zinc 900', value: 'hover:bg-zinc-900' },
      { label: 'hover:bg Zinc 950', value: 'hover:bg-zinc-950' },
      { label: 'hover:bg Neutral 50', value: 'hover:bg-neutral-50' },
      { label: 'hover:bg Neutral 100', value: 'hover:bg-neutral-100' },
      { label: 'hover:bg Neutral 200', value: 'hover:bg-neutral-200' },
      { label: 'hover:bg Neutral 300', value: 'hover:bg-neutral-300' },
      { label: 'hover:bg Neutral 400', value: 'hover:bg-neutral-400' },
      { label: 'hover:bg Neutral 500', value: 'hover:bg-neutral-500' },
      { label: 'hover:bg Neutral 600', value: 'hover:bg-neutral-600' },
      { label: 'hover:bg Neutral 700', value: 'hover:bg-neutral-700' },
      { label: 'hover:bg Neutral 800', value: 'hover:bg-neutral-800' },
      { label: 'hover:bg Neutral 900', value: 'hover:bg-neutral-900' },
      { label: 'hover:bg Neutral 950', value: 'hover:bg-neutral-950' },
      { label: 'hover:bg Stone 50', value: 'hover:bg-stone-50' },
      { label: 'hover:bg Stone 100', value: 'hover:bg-stone-100' },
      { label: 'hover:bg Stone 200', value: 'hover:bg-stone-200' },
      { label: 'hover:bg Stone 300', value: 'hover:bg-stone-300' },
      { label: 'hover:bg Stone 400', value: 'hover:bg-stone-400' },
      { label: 'hover:bg Stone 500', value: 'hover:bg-stone-500' },
      { label: 'hover:bg Stone 600', value: 'hover:bg-stone-600' },
      { label: 'hover:bg Stone 700', value: 'hover:bg-stone-700' },
      { label: 'hover:bg Stone 800', value: 'hover:bg-stone-800' },
      { label: 'hover:bg Stone 900', value: 'hover:bg-stone-900' },
      { label: 'hover:bg Stone 950', value: 'hover:bg-stone-950' },
      { label: 'hover:bg Red 50', value: 'hover:bg-red-50' },
      { label: 'hover:bg Red 100', value: 'hover:bg-red-100' },
      { label: 'hover:bg Red 200', value: 'hover:bg-red-200' },
      { label: 'hover:bg Red 300', value: 'hover:bg-red-300' },
      { label: 'hover:bg Red 400', value: 'hover:bg-red-400' },
      { label: 'hover:bg Red 500', value: 'hover:bg-red-500' },
      { label: 'hover:bg Red 600', value: 'hover:bg-red-600' },
      { label: 'hover:bg Red 700', value: 'hover:bg-red-700' },
      { label: 'hover:bg Red 800', value: 'hover:bg-red-800' },
      { label: 'hover:bg Red 900', value: 'hover:bg-red-900' },
      { label: 'hover:bg Red 950', value: 'hover:bg-red-950' },
      { label: 'hover:bg Orange 50', value: 'hover:bg-orange-50' },
      { label: 'hover:bg Orange 100', value: 'hover:bg-orange-100' },
      { label: 'hover:bg Orange 200', value: 'hover:bg-orange-200' },
      { label: 'hover:bg Orange 300', value: 'hover:bg-orange-300' },
      { label: 'hover:bg Orange 400', value: 'hover:bg-orange-400' },
      { label: 'hover:bg Orange 500', value: 'hover:bg-orange-500' },
      { label: 'hover:bg Orange 600', value: 'hover:bg-orange-600' },
      { label: 'hover:bg Orange 700', value: 'hover:bg-orange-700' },
      { label: 'hover:bg Orange 800', value: 'hover:bg-orange-800' },
      { label: 'hover:bg Orange 900', value: 'hover:bg-orange-900' },
      { label: 'hover:bg Orange 950', value: 'hover:bg-orange-950' },
      { label: 'hover:bg Amber 50', value: 'hover:bg-amber-50' },
      { label: 'hover:bg Amber 100', value: 'hover:bg-amber-100' },
      { label: 'hover:bg Amber 200', value: 'hover:bg-amber-200' },
      { label: 'hover:bg Amber 300', value: 'hover:bg-amber-300' },
      { label: 'hover:bg Amber 400', value: 'hover:bg-amber-400' },
      { label: 'hover:bg Amber 500', value: 'hover:bg-amber-500' },
      { label: 'hover:bg Amber 600', value: 'hover:bg-amber-600' },
      { label: 'hover:bg Amber 700', value: 'hover:bg-amber-700' },
      { label: 'hover:bg Amber 800', value: 'hover:bg-amber-800' },
      { label: 'hover:bg Amber 900', value: 'hover:bg-amber-900' },
      { label: 'hover:bg Amber 950', value: 'hover:bg-amber-950' },
      { label: 'hover:bg Yellow 50', value: 'hover:bg-yellow-50' },
      { label: 'hover:bg Yellow 100', value: 'hover:bg-yellow-100' },
      { label: 'hover:bg Yellow 200', value: 'hover:bg-yellow-200' },
      { label: 'hover:bg Yellow 300', value: 'hover:bg-yellow-300' },
      { label: 'hover:bg Yellow 400', value: 'hover:bg-yellow-400' },
      { label: 'hover:bg Yellow 500', value: 'hover:bg-yellow-500' },
      { label: 'hover:bg Yellow 600', value: 'hover:bg-yellow-600' },
      { label: 'hover:bg Yellow 700', value: 'hover:bg-yellow-700' },
      { label: 'hover:bg Yellow 800', value: 'hover:bg-yellow-800' },
      { label: 'hover:bg Yellow 900', value: 'hover:bg-yellow-900' },
      { label: 'hover:bg Yellow 950', value: 'hover:bg-yellow-950' },
      { label: 'hover:bg Lime 50', value: 'hover:bg-lime-50' },
      { label: 'hover:bg Lime 100', value: 'hover:bg-lime-100' },
      { label: 'hover:bg Lime 200', value: 'hover:bg-lime-200' },
      { label: 'hover:bg Lime 300', value: 'hover:bg-lime-300' },
      { label: 'hover:bg Lime 400', value: 'hover:bg-lime-400' },
      { label: 'hover:bg Lime 500', value: 'hover:bg-lime-500' },
      { label: 'hover:bg Lime 600', value: 'hover:bg-lime-600' },
      { label: 'hover:bg Lime 700', value: 'hover:bg-lime-700' },
      { label: 'hover:bg Lime 800', value: 'hover:bg-lime-800' },
      { label: 'hover:bg Lime 900', value: 'hover:bg-lime-900' },
      { label: 'hover:bg Lime 950', value: 'hover:bg-lime-950' },
      { label: 'hover:bg Green 50', value: 'hover:bg-green-50' },
      { label: 'hover:bg Green 100', value: 'hover:bg-green-100' },
      { label: 'hover:bg Green 200', value: 'hover:bg-green-200' },
      { label: 'hover:bg Green 300', value: 'hover:bg-green-300' },
      { label: 'hover:bg Green 400', value: 'hover:bg-green-400' },
      { label: 'hover:bg Green 500', value: 'hover:bg-green-500' },
      { label: 'hover:bg Green 600', value: 'hover:bg-green-600' },
      { label: 'hover:bg Green 700', value: 'hover:bg-green-700' },
      { label: 'hover:bg Green 800', value: 'hover:bg-green-800' },
      { label: 'hover:bg Green 900', value: 'hover:bg-green-900' },
      { label: 'hover:bg Green 950', value: 'hover:bg-green-950' },
      { label: 'hover:bg Emerald 50', value: 'hover:bg-emerald-50' },
      { label: 'hover:bg Emerald 100', value: 'hover:bg-emerald-100' },
      { label: 'hover:bg Emerald 200', value: 'hover:bg-emerald-200' },
      { label: 'hover:bg Emerald 300', value: 'hover:bg-emerald-300' },
      { label: 'hover:bg Emerald 400', value: 'hover:bg-emerald-400' },
      { label: 'hover:bg Emerald 500', value: 'hover:bg-emerald-500' },
      { label: 'hover:bg Emerald 600', value: 'hover:bg-emerald-600' },
      { label: 'hover:bg Emerald 700', value: 'hover:bg-emerald-700' },
      { label: 'hover:bg Emerald 800', value: 'hover:bg-emerald-800' },
      { label: 'hover:bg Emerald 900', value: 'hover:bg-emerald-900' },
      { label: 'hover:bg Emerald 950', value: 'hover:bg-emerald-950' },
      { label: 'hover:bg Teal 50', value: 'hover:bg-teal-50' },
      { label: 'hover:bg Teal 100', value: 'hover:bg-teal-100' },
      { label: 'hover:bg Teal 200', value: 'hover:bg-teal-200' },
      { label: 'hover:bg Teal 300', value: 'hover:bg-teal-300' },
      { label: 'hover:bg Teal 400', value: 'hover:bg-teal-400' },
      { label: 'hover:bg Teal 500', value: 'hover:bg-teal-500' },
      { label: 'hover:bg Teal 600', value: 'hover:bg-teal-600' },
      { label: 'hover:bg Teal 700', value: 'hover:bg-teal-700' },
      { label: 'hover:bg Teal 800', value: 'hover:bg-teal-800' },
      { label: 'hover:bg Teal 900', value: 'hover:bg-teal-900' },
      { label: 'hover:bg Teal 950', value: 'hover:bg-teal-950' },
      { label: 'hover:bg Cyan 50', value: 'hover:bg-cyan-50' },
      { label: 'hover:bg Cyan 100', value: 'hover:bg-cyan-100' },
      { label: 'hover:bg Cyan 200', value: 'hover:bg-cyan-200' },
      { label: 'hover:bg Cyan 300', value: 'hover:bg-cyan-300' },
      { label: 'hover:bg Cyan 400', value: 'hover:bg-cyan-400' },
      { label: 'hover:bg Cyan 500', value: 'hover:bg-cyan-500' },
      { label: 'hover:bg Cyan 600', value: 'hover:bg-cyan-600' },
      { label: 'hover:bg Cyan 700', value: 'hover:bg-cyan-700' },
      { label: 'hover:bg Cyan 800', value: 'hover:bg-cyan-800' },
      { label: 'hover:bg Cyan 900', value: 'hover:bg-cyan-900' },
      { label: 'hover:bg Cyan 950', value: 'hover:bg-cyan-950' },
      { label: 'hover:bg Sky 50', value: 'hover:bg-sky-50' },
      { label: 'hover:bg Sky 100', value: 'hover:bg-sky-100' },
      { label: 'hover:bg Sky 200', value: 'hover:bg-sky-200' },
      { label: 'hover:bg Sky 300', value: 'hover:bg-sky-300' },
      { label: 'hover:bg Sky 400', value: 'hover:bg-sky-400' },
      { label: 'hover:bg Sky 500', value: 'hover:bg-sky-500' },
      { label: 'hover:bg Sky 600', value: 'hover:bg-sky-600' },
      { label: 'hover:bg Sky 700', value: 'hover:bg-sky-700' },
      { label: 'hover:bg Sky 800', value: 'hover:bg-sky-800' },
      { label: 'hover:bg Sky 900', value: 'hover:bg-sky-900' },
      { label: 'hover:bg Sky 950', value: 'hover:bg-sky-950' },
      { label: 'hover:bg Blue 50', value: 'hover:bg-blue-50' },
      { label: 'hover:bg Blue 100', value: 'hover:bg-blue-100' },
      { label: 'hover:bg Blue 200', value: 'hover:bg-blue-200' },
      { label: 'hover:bg Blue 300', value: 'hover:bg-blue-300' },
      { label: 'hover:bg Blue 400', value: 'hover:bg-blue-400' },
      { label: 'hover:bg Blue 500', value: 'hover:bg-blue-500' },
      { label: 'hover:bg Blue 600', value: 'hover:bg-blue-600' },
      { label: 'hover:bg Blue 700', value: 'hover:bg-blue-700' },
      { label: 'hover:bg Blue 800', value: 'hover:bg-blue-800' },
      { label: 'hover:bg Blue 900', value: 'hover:bg-blue-900' },
      { label: 'hover:bg Blue 950', value: 'hover:bg-blue-950' },
      { label: 'hover:bg Indigo 50', value: 'hover:bg-indigo-50' },
      { label: 'hover:bg Indigo 100', value: 'hover:bg-indigo-100' },
      { label: 'hover:bg Indigo 200', value: 'hover:bg-indigo-200' },
      { label: 'hover:bg Indigo 300', value: 'hover:bg-indigo-300' },
      { label: 'hover:bg Indigo 400', value: 'hover:bg-indigo-400' },
      { label: 'hover:bg Indigo 500', value: 'hover:bg-indigo-500' },
      { label: 'hover:bg Indigo 600', value: 'hover:bg-indigo-600' },
      { label: 'hover:bg Indigo 700', value: 'hover:bg-indigo-700' },
      { label: 'hover:bg Indigo 800', value: 'hover:bg-indigo-800' },
      { label: 'hover:bg Indigo 900', value: 'hover:bg-indigo-900' },
      { label: 'hover:bg Indigo 950', value: 'hover:bg-indigo-950' },
      { label: 'hover:bg Violet 50', value: 'hover:bg-violet-50' },
      { label: 'hover:bg Violet 100', value: 'hover:bg-violet-100' },
      { label: 'hover:bg Violet 200', value: 'hover:bg-violet-200' },
      { label: 'hover:bg Violet 300', value: 'hover:bg-violet-300' },
      { label: 'hover:bg Violet 400', value: 'hover:bg-violet-400' },
      { label: 'hover:bg Violet 500', value: 'hover:bg-violet-500' },
      { label: 'hover:bg Violet 600', value: 'hover:bg-violet-600' },
      { label: 'hover:bg Violet 700', value: 'hover:bg-violet-700' },
      { label: 'hover:bg Violet 800', value: 'hover:bg-violet-800' },
      { label: 'hover:bg Violet 900', value: 'hover:bg-violet-900' },
      { label: 'hover:bg Violet 950', value: 'hover:bg-violet-950' },
      { label: 'hover:bg Purple 50', value: 'hover:bg-purple-50' },
      { label: 'hover:bg Purple 100', value: 'hover:bg-purple-100' },
      { label: 'hover:bg Purple 200', value: 'hover:bg-purple-200' },
      { label: 'hover:bg Purple 300', value: 'hover:bg-purple-300' },
      { label: 'hover:bg Purple 400', value: 'hover:bg-purple-400' },
      { label: 'hover:bg Purple 500', value: 'hover:bg-purple-500' },
      { label: 'hover:bg Purple 600', value: 'hover:bg-purple-600' },
      { label: 'hover:bg Purple 700', value: 'hover:bg-purple-700' },
      { label: 'hover:bg Purple 800', value: 'hover:bg-purple-800' },
      { label: 'hover:bg Purple 900', value: 'hover:bg-purple-900' },
      { label: 'hover:bg Purple 950', value: 'hover:bg-purple-950' },
      { label: 'hover:bg Fuchsia 50', value: 'hover:bg-fuchsia-50' },
      { label: 'hover:bg Fuchsia 100', value: 'hover:bg-fuchsia-100' },
      { label: 'hover:bg Fuchsia 200', value: 'hover:bg-fuchsia-200' },
      { label: 'hover:bg Fuchsia 300', value: 'hover:bg-fuchsia-300' },
      { label: 'hover:bg Fuchsia 400', value: 'hover:bg-fuchsia-400' },
      { label: 'hover:bg Fuchsia 500', value: 'hover:bg-fuchsia-500' },
      { label: 'hover:bg Fuchsia 600', value: 'hover:bg-fuchsia-600' },
      { label: 'hover:bg Fuchsia 700', value: 'hover:bg-fuchsia-700' },
      { label: 'hover:bg Fuchsia 800', value: 'hover:bg-fuchsia-800' },
      { label: 'hover:bg Fuchsia 900', value: 'hover:bg-fuchsia-900' },
      { label: 'hover:bg Fuchsia 950', value: 'hover:bg-fuchsia-950' },
      { label: 'hover:bg Pink 50', value: 'hover:bg-pink-50' },
      { label: 'hover:bg Pink 100', value: 'hover:bg-pink-100' },
      { label: 'hover:bg Pink 200', value: 'hover:bg-pink-200' },
      { label: 'hover:bg Pink 300', value: 'hover:bg-pink-300' },
      { label: 'hover:bg Pink 400', value: 'hover:bg-pink-400' },
      { label: 'hover:bg Pink 500', value: 'hover:bg-pink-500' },
      { label: 'hover:bg Pink 600', value: 'hover:bg-pink-600' },
      { label: 'hover:bg Pink 700', value: 'hover:bg-pink-700' },
      { label: 'hover:bg Pink 800', value: 'hover:bg-pink-800' },
      { label: 'hover:bg Pink 900', value: 'hover:bg-pink-900' },
      { label: 'hover:bg Pink 950', value: 'hover:bg-pink-950' },
      { label: 'hover:bg Rose 50', value: 'hover:bg-rose-50' },
      { label: 'hover:bg Rose 100', value: 'hover:bg-rose-100' },
      { label: 'hover:bg Rose 200', value: 'hover:bg-rose-200' },
      { label: 'hover:bg Rose 300', value: 'hover:bg-rose-300' },
      { label: 'hover:bg Rose 400', value: 'hover:bg-rose-400' },
      { label: 'hover:bg Rose 500', value: 'hover:bg-rose-500' },
      { label: 'hover:bg Rose 600', value: 'hover:bg-rose-600' },
      { label: 'hover:bg Rose 700', value: 'hover:bg-rose-700' },
      { label: 'hover:bg Rose 800', value: 'hover:bg-rose-800' },
      { label: 'hover:bg Rose 900', value: 'hover:bg-rose-900' },
      { label: 'hover:bg Rose 950', value: 'hover:bg-rose-950' },
      // hhorizontal padding and vertical padding (px and py)
      { label: 'Padding X 1', value: 'px-1' },
      { label: 'Padding X 2', value: 'px-2' },
      { label: 'Padding X 3', value: 'px-3' },
      { label: 'Padding X 4', value: 'px-4' },
      { label: 'Padding X 5', value: 'px-5' },
      { label: 'Padding X 6', value: 'px-6' },
      { label: 'Padding X 7', value: 'px-7' },
      { label: 'Padding X 8', value: 'px-8' },
      { label: 'Padding X 9', value: 'px-9' },
      { label: 'Padding X 10', value: 'px-10' },
      { label: 'Padding X 11', value: 'px-11' },
      { label: 'Padding X 12', value: 'px-12' },
      { label: 'Padding X 14', value: 'px-14' },
      { label: 'Padding X 16', value: 'px-16' },
      { label: 'Padding X 20', value: 'px-20' },
      { label: 'Padding Y 1', value: 'py-1' },
      { label: 'Padding Y 2', value: 'py-2' },
      { label: 'Padding Y 3', value: 'py-3' },
      { label: 'Padding Y 4', value: 'py-4' },
      { label: 'Padding Y 5', value: 'py-5' },
      { label: 'Padding Y 6', value: 'py-6' },
      { label: 'Padding Y 7', value: 'py-7' },
      { label: 'Padding Y 8', value: 'py-8' },
      { label: 'Padding Y 9', value: 'py-9' },
      { label: 'Padding Y 10', value: 'py-10' },
      { label: 'Padding Y 11', value: 'py-11' },
      { label: 'Padding Y 12', value: 'py-12' },
      { label: 'Padding Y 14', value: 'py-14' },
      { label: 'Padding Y 16', value: 'py-16' },
      { label: 'Padding Y 20', value: 'py-20' },
      // text sizes
      { label: 'Text xs', value: 'text-xs' },
      { label: 'Text sm', value: 'text-sm' },
      { label: 'Text normal', value: 'text-base' },
      { label: 'Text lg', value: 'text-lg' },
      { label: 'Text xl', value: 'text-xl' },
      { label: 'Text 2xl', value: 'text-2xl' },
      { label: 'Text 3xl', value: 'text-3xl' },
      { label: 'Text 4xl', value: 'text-4xl' },
      { label: 'Text 5xl', value: 'text-5xl' },
      { label: 'Text 6xl', value: 'text-6xl' },
      // variations for text sizes on different screen sizes
      // font weights
      { label: 'Font Weight 100', value: 'font-thin' },
      { label: 'Font Weight 200', value: 'font-extralight' },
      { label: 'Font Weight 300', value: 'font-light' },
      { label: 'Font Weight 400', value: 'font-normal' },
      { label: 'Font Weight 500', value: 'font-medium' },
      { label: 'Font Weight 600', value: 'font-semibold' },
      { label: 'Font Weight 700', value: 'font-bold' },
      { label: 'Font Weight 800', value: 'font-extrabold' },
      { label: 'Font Weight 900', value: 'font-black' },
    ],
  }

  return deepMerge(buttonResult, overrides)
}
